name: ci-build
on:
  pull_request:
    branches:
      - "master"
    types:
      - "closed"
env:
  APP_VERSION: 1.0.0
jobs:
  biuld:
    runs-on: ubuntu-latest
    steps:
      - name: récupération du repo
        uses: action/checkout@v3
      - name: Installation Docker QEMU
        uses: docker/setup-qemu-action@v1
      - name: Installation docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build & push docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/weather:1.0.0'