name: ci
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: récupération du repository
        uses: actions/checkout@v3
      - name: installation de node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: installation de dépendences
        run: npm i
      - name: test unitaires
        run: npm run test
      - name: coverage
        run: npm run cober
